### ISSUE TITLE
file type is not checked correclty in create_gif

### ISSUE THREAD

**Issue by BouchardClaude** [dylanwal/plotly_gif#1]
in create_gif function, a out gif filename can be specified and the extension is checked for ".gif"

`        if gif_path is None:
            gif_path = self.gif_path / "fig.gif" if self.gif_name is None else self.gif_path / self.gif_name
        else:
            if gif_path.endswith(".gif"):
                raise ValueError(f"gif path must end with '.gif'. Provide value: {gif_path}")`

buf the if will make the program fail if the valid extenstion is provided ( or I dont understant it correclty?)
Simple fix would be to invert the if at line 153 of gif.py

thanks!

**Comment by dylanwal** [comment]
You were right! Thanks for catching the bug. It is now fixed.
