### ISSUE TITLE
Relative imports for `requirements.txt`

### ISSUE THREAD

**Issue by Anselmoo** [dylanwal/plotly_gif#3]
@dylanwal very nice and helpful plugin

I was wondering if it might be possible to replace the `==` _pinned requirements_ with `>=` _relative imports_?

https://github.com/dylanwal/plotly_gif/blob/53c0fbabccf8bc7db54ae61b24c9fea6c7f12569/requirements.txt#L1-L4

Adding support for `poetry` in addition to `pyproject.toml` could enhance compatibility.

**Comment by dylanwal** [comment]
Hi @Anselmoo thanks for reaching out!

It was my understanding that the 'requirements.txt' should be `==` and the 'setup.cfg' uses `>='.
I believe the rational behind this is that when the package is `pip` installed it gets versions from 'setup.cfg' and the user will get the most up-to-date versions. The 'requirements.txt' is there as a back-up in case there was breaking changes in dependances and for development. If you have a different perspective on this, let me know.

With regard to `poetry`: I haven't used that package manger before (I am aware of it), and I can look into adding that next week or if that's something you can put together I would be happy to accept the pull request.

**Comment by Anselmoo** [comment]
Dear @dylanwal, 
Thank you very much for your feedback! Sorry, I wasn't aware about `requirements.txt` vs. `setup.cfg`. You are right, https://pypi.org/project/plotly-gif/#files is only taking the `setup.cfg`.

<img width="225" alt="image" src="https://github.com/dylanwal/plotly_gif/assets/13209783/a30da886-66f5-4843-9158-105405eef199">

However, I am happy to make PR for [Poetry](https://python-poetry.org/docs/configuration/) as package manager, so you can take a look.
